# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20170922_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('ComNUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.ComTable')),
            ],
        ),
    ]
