# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidtable',
            name='invNUM',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, to='myApp.invTable'),
        ),
    ]
