# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_bidtable_invnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='price',
            new_name='pricing',
        ),
    ]
