# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20170922_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='state',
            field=models.IntegerField(),
        ),
    ]
