# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20170923_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='optmpath',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
