# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_ordertable_optmpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='optmpath',
            field=models.CharField(max_length=100),
        ),
    ]
