# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20170923_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='costTime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='loginfo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
