# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_auto_20170923_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='custtable',
            name='CustName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='receiver',
            field=models.CharField(default='hehe', max_length=20),
            preserve_default=False,
        ),
    ]
